- name: Lookup Plugin Lines Demo
  hosts: localhost          
  gather_facts: no          
  tasks:                    
  - name: Print with loop OBSOLETE
    debug:                  
      msg: "{{ item }}"     
    when: item.find('servera') != -1
    with_lines:             
    - cat /etc/hosts        
                            
                            
  - name: Search with query plugin LEARN NEW WAY
    debug:                  
      msg: "{{ item }}"     
    loop: "{{ query('lines', 'cat /etc/hosts') }}"
    when: item.find('servera') != -1

