- name: Configuration Playbook
  hosts: servera*
  remote_user: devops
  become: false
  tasks:
  - name: Task Outside Block 1
    debug:
      msg: "Hello i am outside"
  - name: Open Firewall Port
    firewalld:
      service: http
      immediate: yes
      permanent: yes
      state: enabled
    become: true
       
  - name: Block for Web Server Tasks
    block:
      - name: Install Package Task
        yum:
          name: httpd
          state: present
      - name: Create file task
        copy:
          content: "Hello Ansible Playbook"
          dest: "/var/www/html/first.html"
      - name: Start httpd service
        service:
          name: httpd
          state: restarted
    become: true
    when: ansible_distribution == "RedHat"
    rescue:
      - name: rollback install
        yum:
          name: httpd
          state: absent
        become: true
      - name: rollback cnahed config
        debug:
          msg: "Hey uninstall changed configsk"
    always:
      - name: EMAIL stakeholders
        debug:
          msg: "EMAIL  to my clients"
       
  - name: Task Outside Block 2
    debug:
      msg: "Hello i am outside TOO"
