- name: Check Variable Level
  hosts: all
  gather_facts: no
  vars:
    variable_level: "Level 12"
  vars_prompt:
  - name: variable_level
    prompt: "Enter Variable Value Please"
    private: no
       
  vars_files:
  - /home/student/sec/custom_vars.yml
       
  #roles:
  #- role: variable_role
  tasks:
  - name: Set a Fact Value
    set_fact:
      variable_level: "Level 19"
       
  - name: Include a variable File
    include_vars: newvars.yml
       
  - name: Block for Showing Variable
    block:
      - name: Import a ROLE
        import_role:
          name: variable_role
        vars:
          variable_level: "Level 17"
       
      - name: Include a ROLE
        include_role:
          name: variable_role
        vars:
          variable_level: "Level 20"
      - name: TTTTTTTTTTTTT
        debug:
          msg: "{{ variable_level }}"
    vars:
      variable_level: "Level 16"
