- name: Variable Demo for class
  hosts: prod
  #,dev
  gather_facts: no
 
 
  vars:
    texas_var: "Level12_Playbook_vars"

  vars_prompt:
  ##   Level13_Playbook_vars_prompt ##
  - name: texas_var
    prompt: Enter the Value
    private: no
 
  vars_files:
  - /home/student/texas/outside_vars.yml
 
  roles:
  - role: variable_role
 
  tasks:
  - name: Set the FACT
    set_fact:
      texas_var: "Level19_set_fact_Module"
  - name: Includ the extra VARIBLE FILE
    include_vars:
      file: include_extra_vars.yml
  - name: Include the role from outside
    include_role:
      name: variable_role
    vars:
      texas_var: "Level20_include_role_Module"
 
  - name: Block for Variable
    block:
        - name: Just a Task1
          debug:
            msg: "{{ texas_var }}"
          vars:
            texas_var: "Level17_Playbook_TASK_vars"
 
        - name: Just a Task2
          debug:
            msg: "{{ texas_var }}"
    vars:
      texas_var: "Level16_Playbook_BLOCK_vars"
